### ISSUE TITLE
Remove event tries to remove entities with _id NULL

### ISSUE THREAD

**Issue by vokrik** [Kdyby/DoctrineSearch#4]
Hi @fprochazka ,
There might be a problem with the preRemove event in OrmSearchableListener.

When I remove an entity, the preRemove event is called and schedules a remove from elastic search. However the flush is done after postFlush, which means, that the id of the Entity is already NULL.

Example:

```
public function prePersist(LifecycleEventArgs $oArgs)
{
    $oEntity = $oArgs->getEntity();
    if ($oEntity instanceof Searchable) {
        $this->sm->persist($oEntity);
    }
}

public function postFlush()
{
    $this->sm->flush();
}
```

This results in this call:
     `Request:  array (1)
      delete => array (1)
      _id => ""`

However:

```
public function prePersist(LifecycleEventArgs $oArgs)
{
    $oEntity = $oArgs->getEntity();
    if ($oEntity instanceof Searchable) {
        $this->sm->persist($oEntity);
        $this->sm->flush()
    }
}
```

results in 
     `Request:  array (1)
      delete => array (1)
      _id => 4`

Am I forgetting something or is it a bug?

**Comment by vokrik** [comment]
I think I found a solution to this. When we clone the entity we want to remove from elasticsearch, the ID will stay even after the flush of the original entity, because they are different instances now.

here is how it looks:


	public function preRemove(LifecycleEventArgs $oArgs)
	{
		$oEntity = $oArgs->getEntity();
		if ($oEntity instanceof Searchable) {
			$copyOEntity = clone $oEntity;
			$this->sm->remove($copyOEntity);
		}
	}

**Comment by fprochazka** [comment]
Sorry, but this package was an experiment and now is deprecated.
