### ISSUE TITLE
Faster index creation

### ISSUE THREAD

**Issue by danielkucera** [Kdyby/DoctrineSearch#7]
https://github.com/Kdyby/DoctrineSearch/blob/74237e55b8906a870dd684b5e463e19d7a549826/src/Kdyby/DoctrineSearch/River/DefaultEntityRiver.php#L95

Code starting on this line causes builder to build queries with sorted IDs, with SQL ending e.g.: u0_.id > 14741 ORDER BY u0_.id ASC LIMIT 1000 which is slow on huge tables.

Since we don't need page of exact size, it would be better (and faster) to build queries like this:
u0_.id > 14741 AND u0_.id < 15741;

This will result in selects of maximum size of 1000 rows but in our environment it's significantly faster (80sec vs 0.003sec)

**Comment by enumag** [comment]
Sounds good. Feel free to send a PR!
